<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AddresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddresRepository extends EntityRepository
{
}
